### ISSUE TITLE
Use in a controller

### ISSUE THREAD

**Issue by marvi** [sjurgemeyer/grails-jxl-plugin#3]
Nice work! 

In your examples you create a file. Can it be used in a controller, returning Excel to the web browser? Or do I have to cerate a file on the server before returning it?

**Comment by sjurgemeyer** [comment]
I added a renderExcel method to controllers in version 0.52.  There's an example on the wiki.  Unfortunately you will have to add the Mixin to the controller to make it work, but other than that it's pretty straightforward.

**Comment by marvi** [comment]
Thanks! Perfect.
